# Sección 1 — Carga de datos    
En Google Colab existen dos formas habituales de trabajar con archivos:   
 *   Subir el archivo manualmente
 *   Acceder al archivo desde Google Drive

## Opción A — Subida manual del archivo csv  
Primero, subir el archivo desde el panel lateral izquierdo de Colab:   
   Files → Upload → seleccionar CSV

In [91]:
data <- read.csv(
  "/content/Hospital_4.csv",
  quote = "\"",
  fill = TRUE
)

In [92]:
dim(data)

[1] 15345    34

In [93]:
summary(data)

   Patient.ID       Heart.Rate     Respiratory.Rate     Timestamp
 Min.   :    15   Min.   : 39.00   Min.   :12.00    Length   :15345
 1st Qu.: 50183   1st Qu.: 70.00   1st Qu.:14.00    N.unique :13913
 Median : 99463   Median : 80.00   Median :16.00    N.blank  : 1326
 Mean   :100097   Mean   : 79.51   Mean   :15.52    Min.nchar:    0
 3rd Qu.:150499   3rd Qu.: 89.00   3rd Qu.:18.00    Max.nchar:   26
 Max.   :200008   Max.   :167.00   Max.   :43.00
 NAs    :1799     NAs    :1786     NAs    :1808
 Body.Temperature Oxygen.Saturation Systolic.Blood.Pressure
 Min.   :36.00    Min.   : 70.11    Min.   :110.0
 1st Qu.:36.36    1st Qu.: 96.28    1st Qu.:117.0
 Median :36.75    Median : 97.52    Median :124.0
 Mean   :36.75    Mean   : 97.49    Mean   :124.5
 3rd Qu.:37.12    3rd Qu.: 98.75    3rd Qu.:132.0
 Max.   :37.50    Max.   :100.00    Max.   :188.0
 NAs    :1804     NAs    :1763      NAs    :1811
 Diastolic.Blood.Pressure      Age              Gender       Weight..kg.
 Min.   : 70.0            Min.   :18.00   Length   :15345   Min.   :50.01
 1st Qu.: 74.0            1st Qu.:36.00   N.unique :  378   1st Qu.:62.43
 Median : 79.0            Median :53.00   N.blank  : 1326   Median :75.00
 Mean   : 79.5            Mean   :53.49   Min.nchar:    0   Mean   :75.02
 3rd Qu.: 84.0            3rd Qu.:71.00   Max.nchar:    9   3rd Qu.:87.71
 Max.   :117.0            Max.   :89.00                     Max.   :99.99
 NAs    :1798             NAs    :1803                      NAs    :1801
   Height..m.     Derived_HRV      Derived_Pulse_Pressure  Derived_BMI
 Min.   :1.500   Min.   :0.05000   Min.   :21.00          Min.   :12.59
 1st Qu.:1.626   1st Qu.:0.07514   1st Qu.:38.00          1st Qu.:20.16
 Median :1.752   Median :0.09993   Median :45.00          Median :24.30
 Mean   :1.751   Mean   :0.10014   Mean   :44.97          Mean   :24.96
 3rd Qu.:1.875   3rd Qu.:0.12504   3rd Qu.:53.00          3rd Qu.:29.19
 Max.   :2.000   Max.   :0.42810   Max.   :69.00          Max.   :44.19
 NAs    :1802    NAs    :1809      NAs    :1813           NAs    :1802
  Derived_MAP       Risk.Category        Hospital      Empty_Int_Column
 Min.   : 83.33   Length   :15345   Length   :15345   Length   :15345
 1st Qu.: 91.00   N.unique :  383   N.unique :    1   N.unique :  385
 Median : 94.33   N.blank  : 1326   N.blank  :    0   N.blank  :14847
 Mean   : 94.48   Min.nchar:    0   Min.nchar:   10   Min.nchar:    0
 3rd Qu.: 98.00   Max.nchar:    9   Max.nchar:   10   Max.nchar:    9
 Max.   :105.67
 NAs    :1796
     Diagnosis       Smoking.Status  Physical.Activity.Level  Medication.Type
 Length   :15345   Length   :15345   Length   :15345         Length   :15345
 N.unique :    5   N.unique :    3   N.unique :   14         N.unique :   13
 N.blank  :    0   N.blank  :    0   N.blank  : 1244         N.blank  :  282
 Min.nchar:    4   Min.nchar:    5   Min.nchar:    0         Min.nchar:    0
 Max.nchar:   15   Max.nchar:    7   Max.nchar:    8         Max.nchar:   17


       Region      Socioeconomic.Level     Occupation          Shift
 Length   :15345   Length   :15345     Length   :15345   Length   :15345
 N.unique :   10   N.unique :    3     N.unique :   10   N.unique :    3
 N.blank  :  315   N.blank  :    0     N.blank  :  329   N.blank  :    0
 Min.nchar:    0   Min.nchar:    3     Min.nchar:    0   Min.nchar:    5
 Max.nchar:   10   Max.nchar:    6     Max.nchar:   13   Max.nchar:    9


       Season         Glucose       Cholesterol    Triglycerides
 Length   :15345   Min.   : 37.9   Min.   : 91.6   Min.   : 40.2
 N.unique :    4   1st Qu.: 92.2   1st Qu.:181.8   1st Qu.:140.7
 N.blank  :    0   Median :104.1   Median :206.9   Median :180.9
 Min.nchar:    6   Mean   :114.8   Mean   :210.4   Mean   :193.4
 Max.nchar:    6   3rd Qu.:120.4   3rd Qu.:235.4   3rd Qu.:239.8
                   Max.   :414.4   Max.   :373.7   Max.   :546.1

   Hemoglobin      Creatinine    Injected.Multivariate.Outlier
 Min.   : 7.70   Min.   :0.400   Mode :logical
 1st Qu.:13.20   1st Qu.:0.960   FALSE:15321
 Median :14.30   Median :1.170   TRUE :24
 Mean   :14.18   Mean   :1.243
 3rd Qu.:15.30   3rd Qu.:1.420
 Max.   :20.90   Max.   :7.320

# Sección 2 — Inspección inicial del dataset

## 1) **Exploración**: En esta sección realizaremos una exploración preliminar del dataset para conocer:    

- su tamaño   
- sus variables   
- su estructura   
- un resumen general de su contenido

In [94]:
# dim() devuelve dimensiones del dataset: filas y columnas
dim(data)

# nrow() devuelve únicamente la cantidad de filas (registros)
nrow(data)

# ncol() devuelve únicamente la cantidad de columnas (variables)
ncol(data)

# names() muestra los nombres de todas las variables
names(data)

[1] 15345    34

[1] 15345

[1] 34

 [1] "Patient.ID"                    "Heart.Rate"
 [3] "Respiratory.Rate"              "Timestamp"
 [5] "Body.Temperature"              "Oxygen.Saturation"
 [7] "Systolic.Blood.Pressure"       "Diastolic.Blood.Pressure"
 [9] "Age"                           "Gender"
[11] "Weight..kg."                   "Height..m."
[13] "Derived_HRV"                   "Derived_Pulse_Pressure"
[15] "Derived_BMI"                   "Derived_MAP"
[17] "Risk.Category"                 "Hospital"
[19] "Empty_Int_Column"              "Diagnosis"
[21] "Smoking.Status"                "Physical.Activity.Level"
[23] "Medication.Type"               "Region"
[25] "Socioeconomic.Level"           "Occupation"
[27] "Shift"                         "Season"
[29] "Glucose"                       "Cholesterol"
[31] "Triglycerides"                 "Hemoglobin"
[33] "Creatinine"                    "Injected.Multivariate.Outlier"

In [95]:
# str() muestra la estructura interna del dataset:  # tipo de variable, nombre y ejemplos de valores
str(data)

'data.frame':	15345 obs. of  34 variables:
 $ Patient.ID                   : int  15 25 46 50 59 66 76 80 124 134 ...
 $ Heart.Rate                   : int  98 80 71 60 61 60 72 80 60 73 ...
 $ Respiratory.Rate             : int  12 19 14 12 13 13 16 13 14 15 ...
 $ Timestamp                    : chr  "2024-07-19 21:39:45.729841" "2024-07-19 21:29:45.729841" "2024-07-19 21:08:45.729841" "2024-07-19 21:04:45.729841" ...
 $ Body.Temperature             : num  37.3 36.9 37.4 36.4 36.5 ...
 $ Oxygen.Saturation            : num  98.7 99.5 97.5 95.3 97.9 ...
 $ Systolic.Blood.Pressure      : int  127 117 126 119 139 125 110 128 119 114 ...
 $ Diastolic.Blood.Pressure     : int  87 77 84 88 85 76 88 79 84 70 ...
 $ Age                          : int  89 62 77 80 42 51 80 61 20 72 ...
 $ Gender                       : chr  "Female" "MALE" "Male" "Femenino" ...
 $ Weight..kg.                  : num  97.4 71.2 90.6 66.4 63.8 ...
 $ Height..m.                   : num  1.9 1.71 1.63 1.55 1.53 ...
 $ Derived_HRV                  : num  0.138 0.142 0.146 0.137 0.119 ...
 $ Derived_Pulse_Pressure       : int  40 40 42 31 54 49 22 49 35 44 ...
 $ Derived_BMI                  : num  27 24.4 34.2 27.8 27.1 ...
 $ Derived_MAP                  : num  100.3 90.3 98 98.3 103 ...
 $ Risk.Category                : chr  "High Risk" "Low Risk" "High Risk" "Low Risk" ...
 $ Hospital                     : chr  "Hospital 4" "Hospital 4" "Hospital 4" "Hospital 4" ...
 $ Empty_Int_Column             : chr  "" "" "" "" ...
 $ Diagnosis                    : chr  "Healthy" "Healthy" "Hypertension" "Diabetes" ...
 $ Smoking.Status               : chr  "Never" "Never" "Never" "Former" ...
 $ Physical.Activity.Level      : chr  "???" "moderate" "" "Moderate" ...
 $ Medication.Type              : chr  "None" "None" "beta blockers" "None" ...
 $ Region                       : chr  "urban" "Rural" "Urban" "Semiurban" ...
 $ Socioeconomic.Level          : chr  "Low" "Low" "Middle" "Middle" ...
 $ Occupation                   : chr  "office worker" "N/A" "Student" "Student" ...
 $ Shift                        : chr  "Morning" "Afternoon" "Morning" "Afternoon" ...
 $ Season                       : chr  "Winter" "Spring" "Winter" "Autumn" ...
 $ Glucose                      : num  114 112 103 222 116 ...
 $ Cholesterol                  : num  211 266 173 231 214 ...
 $ Triglycerides                : num  189 163 346 201 162 ...
 $ Hemoglobin                   : num  13.8 15 15.9 14 16.8 15.1 15.3 11.5 13.9 13.7 ...
 $ Creatinine                   : num  1.7 0.96 4.04 1.03 1.26 0.94 0.8 0.6 1.51 1.52 ...
 $ Injected.Multivariate.Outlier: logi  FALSE FALSE FALSE FALSE FALSE FALSE ...

cuidado con sheet controlar la importación de datos- muchas veces carga con errores-   
forzado de columnas como texto

In [96]:
# head(data, 10) muestra 10 filas
head(data, 10)

   Patient.ID Heart.Rate Respiratory.Rate Timestamp
1   15        98         12               2024-07-19 21:39:45.729841
2   25        80         19               2024-07-19 21:29:45.729841
3   46        71         14               2024-07-19 21:08:45.729841
4   50        60         12               2024-07-19 21:04:45.729841
5   59        61         13               2024-07-19 20:55:45.729841
6   66        60         13               2024-07-19 20:48:45.729841
7   76        72         16               2024-07-19 20:38:45.729841
8   80        80         13               2024-07-19 20:34:45.729841
9  124        60         14               2024-07-19 19:50:45.729841
10 134        73         15               2024-07-19 19:40:45.729841
   Body.Temperature Oxygen.Saturation Systolic.Blood.Pressure
1  37.26153         98.67484          127
2  36.86324         99.51951          117
3  37.44475         97.53558          126
4  36.36975         95.34457          119
5  36.53399         97.89955          139
6  37.06511         99.02602          125
7  36.42275         98.23353          110
8  36.72886         99.16043          128
9  36.08462         98.57405          119
10 36.51093         98.40727          114
   Diastolic.Blood.Pressure Age Gender    ⋯ Socioeconomic.Level Occupation
1  87                       89  Female    ⋯ Low                 office worker
2  77                       62  MALE      ⋯ Low                 N/A
3  84                       77  Male      ⋯ Middle              Student
4  88                       80  Femenino  ⋯ Middle              Student
5  85                       42  Male      ⋯ Middle              Office
6  76                       51  Female    ⋯ Middle              retird
7  88                       80  Male      ⋯ Low                 office worker
8  79                       61  Female    ⋯ Middle              Manual labor
9  84                       20  FEMALE    ⋯ Low                 retird
10 70                       72  Masculino ⋯ Middle              Retired
   Shift     Season Glucose Cholesterol Triglycerides Hemoglobin Creatinine
1  Morning   Winter 114.2   210.8       188.9         13.8       1.70
2  Afternoon Spring 111.8   266.1       162.6         15.0       0.96
3  Morning   Winter 103.1   173.0       346.4         15.9       4.04
4  Afternoon Autumn 221.7   231.0       200.8         14.0       1.03
5  Afternoon Winter 116.3   213.9       162.5         16.8       1.26
6  Morning   Summer 132.5   148.7       182.6         15.1       0.94
7  Morning   Autumn 126.0   168.1       147.8         15.3       0.80
8  Afternoon Summer 207.7   203.0       265.1         11.5       0.60
9  Morning   Winter  98.6   159.8       215.2         13.9       1.51
10 Afternoon Winter 103.6   287.3       306.8         13.7       1.52
   Injected.Multivariate.Outlier
1  FALSE
2  FALSE
3  FALSE
4  FALSE
5  FALSE
6  FALSE
7  FALSE
8  FALSE
9  FALSE
10 FALSE

In [97]:
library(dplyr)

n_distinct(data$Patient.ID)

[1] 13523

## VOLVAMOS A USAR DATA PARA LIMPIAR

## 2) **Duplicados**: Filas completamente iguales.

In [98]:
# duplicated() marca filas repetidas
duplicados_exactos <- sum(duplicated(data))
duplicados_exactos

[1] 10

In [99]:
# Detectar Patient ID repetidos
sum(duplicated(data$Patient.ID))

[1] 1822

In [100]:
# Mostrar IDs repetidos
data$Patient.ID[duplicated(data$Patient.ID)]

   [1]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
  [11]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
  [21]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
  [31]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
  [41]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
  [51]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
  [61]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
  [71]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
  [81]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
  [91]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [101]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [111]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [121]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [131]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [141]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [151]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [161]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [171]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [181]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [191]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [201]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [211]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [221]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [231]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [241]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [251]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [261]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [271]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [281]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [291]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [301]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [311]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [321]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [331]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [341]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [351]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [361]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [371]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [381]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [391]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [401]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [411]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [421]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [431]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [441]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [451]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [461]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [471]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [481]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [491]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [501]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [511]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [521]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [531]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [541]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [551]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [561]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [571]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [581]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [591]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [601]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [611]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [621]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [631]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [641]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [651]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [661]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [671]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [681]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [691]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [701]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [711]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [721]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [731]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [741]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [751]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [761]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [771]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [781]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [791]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [801]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [811]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [821]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [831]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [841]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [851]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [861]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [871]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [881]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [891]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [901]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [911]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [921]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [931]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [941]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [951]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [961]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [971]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [981]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
 [991]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1001]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1011]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1021]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1031]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1041]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1051]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1061]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1071]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1081]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1091]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1101]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1111]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1121]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1131]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1141]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1151]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1161]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1171]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1181]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1191]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1201]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1211]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1221]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1231]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1241]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1251]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1261]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1271]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1281]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1291]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1301]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1311]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1321]     NA     NA     NA     NA     NA     NA     NA     NA     NA  50305
[1331]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1341]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1351]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1361]     NA     NA     NA     NA     NA     NA  54691     NA     NA     NA
[1371]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1381]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1391]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1401]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1411]     NA     NA     NA     NA     NA     NA  90168     NA     NA     NA
[1421]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1431]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1441]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1451]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1461]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1471]     NA     NA     NA     NA     NA     NA     NA     NA     NA 142932
[1481]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1491]     NA     NA     NA     NA 116269     NA     NA     NA 164956     NA
[1501] 182259     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1511]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1521]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1531]     NA     NA     NA     NA     NA     NA     NA     NA  38664     NA
[1541]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1551]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1561]     NA     NA     NA     NA     NA     NA   2271     NA     NA     NA
[1571]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1581]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1591]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1601]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1611]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1621]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1631]     NA 168455     NA     NA     NA     NA     NA     NA     NA     NA
[1641]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1651]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1661]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1671]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1681]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1691]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1701]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1711]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1721]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1731]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1741]     NA     NA     NA     NA     NA     NA     NA     NA 146076     NA
[1751]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1761]     NA  89710     NA 106810  72293     NA 171495     NA     NA     NA
[1771]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1781]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1791]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1801]     NA     NA     NA     NA     NA     NA     NA     NA     NA     NA
[1811]     NA     NA  49537 104552     NA  84446 157086  24684 194027 120615
[1821] 185310   4277

## 3) Variables redundantes
Buscamos columnas problemáticas:

- vacías
- constantes
- derivadas
- sin variabilidad

In [101]:
# Detectar columnas completamente vacías
sapply(data, function(x) all(is.na(x)))

                   Patient.ID                    Heart.Rate
                        FALSE                         FALSE
             Respiratory.Rate                     Timestamp
                        FALSE                         FALSE
             Body.Temperature             Oxygen.Saturation
                        FALSE                         FALSE
      Systolic.Blood.Pressure      Diastolic.Blood.Pressure
                        FALSE                         FALSE
                          Age                        Gender
                        FALSE                         FALSE
                  Weight..kg.                    Height..m.
                        FALSE                         FALSE
                  Derived_HRV        Derived_Pulse_Pressure
                        FALSE                         FALSE
                  Derived_BMI                   Derived_MAP
                        FALSE                         FALSE
                Risk.Category                      Hospital
                        FALSE                         FALSE
             Empty_Int_Column                     Diagnosis
                        FALSE                         FALSE
               Smoking.Status       Physical.Activity.Level
                        FALSE                         FALSE
              Medication.Type                        Region
                        FALSE                         FALSE
          Socioeconomic.Level                    Occupation
                        FALSE                         FALSE
                        Shift                        Season
                        FALSE                         FALSE
                      Glucose                   Cholesterol
                        FALSE                         FALSE
                Triglycerides                    Hemoglobin
                        FALSE                         FALSE
                   Creatinine Injected.Multivariate.Outlier
                        FALSE                         FALSE

In [102]:
library(tidyverse)

# Unificar celdas vacías, ???, N/A y espacios para que sean todos NA de R
data_unificado <- data %>%
  mutate(across(where(is.character), ~ ifelse(. %in% c("", " ", "???", "N/A", "n/a"), NA, .)))
# Ver la tabla actualizada de NAs reales por columna
colSums(is.na(data_unificado))

                   Patient.ID                    Heart.Rate
                         1799                          1786
             Respiratory.Rate                     Timestamp
                         1808                          1326
             Body.Temperature             Oxygen.Saturation
                         1804                          1763
      Systolic.Blood.Pressure      Diastolic.Blood.Pressure
                         1811                          1798
                          Age                        Gender
                         1803                          1326
                  Weight..kg.                    Height..m.
                         1801                          1802
                  Derived_HRV        Derived_Pulse_Pressure
                         1809                          1813
                  Derived_BMI                   Derived_MAP
                         1802                          1796
                Risk.Category                      Hospital
                         1326                             0
             Empty_Int_Column                     Diagnosis
                        14847                             0
               Smoking.Status       Physical.Activity.Level
                            0                          2755
              Medication.Type                        Region
                          591                           645
          Socioeconomic.Level                    Occupation
                            0                           515
                        Shift                        Season
                            0                             0
                      Glucose                   Cholesterol
                            0                             0
                Triglycerides                    Hemoglobin
                            0                             0
                   Creatinine Injected.Multivariate.Outlier
                            0                             0

In [103]:
# Eliminación de columnas redundantes, vacías y auxiliares
data_filtrado <- data_unificado %>%
  select(
    -matches("Empty_Int_Column"),           # Elimina columna vacía
    -matches("^Hospital$"),                 # Elimina columna constante
    -matches("Injected.Multivariate.Outlier") # Elimina bandera sintética
  )
  # Comparar cantidad de columnas antes y después
ncol(data_unificado) # Tenía 34 columnas
ncol(data_filtrado)  # Ahora debe tener 31 columnas

[1] 34

[1] 31

In [104]:
# Filas completamente vacías
# Para cada fila verificamos si todos sus valores son NA
filas_todo_na <- apply(data, 1, function(x) all(is.na(data_unificado)))

# Cantidad de filas completamente vacías
sum(filas_todo_na)

[1] 0

## 4) Datos sucios
Acá buscamos errores de carga y problemas de categorías.

In [105]:
# Ver categorías observadas
table(data$Physical.Activity.Level)

             low       ???     h1gh     High     HIGH      Low      LoW
    1244      621      314      425     2485      941     2233      459
     LOW      lwo moderate Moderate  modrate      N/A
     791      324     1038     2809      464     1197

In [106]:
# Definimos las variables cualitativas donde el personal del hospital suele escribir
variables_texto <- c(
  "Gender",
  "Diagnosis",
  "Smoking.Status",
  "Physical.Activity.Level",
  "Medication.Type",
  "Region",
  "Socioeconomic.Level",
  "Occupation",
  "Shift",
  "Season",
  "Risk.Category"
)

# Aplicamos la función table() a todas esas columnas a la vez
# Usamos useNA = "always" para que también nos muestre si hay celdas vacías (NA)
lapply(data[variables_texto], table, useNA = "always")

$Gender

          ERROR_102 ERROR_105 ERROR_106 ERROR_108 ERROR_109 ERROR_112 ERROR_114
     1326         1         2         1         1         2         1         2
ERROR_115 ERROR_117 ERROR_118 ERROR_119 ERROR_121 ERROR_122 ERROR_125 ERROR_126
        1         1         2         2         1         2         2         1
ERROR_128 ERROR_132 ERROR_133 ERROR_134 ERROR_140 ERROR_144 ERROR_145 ERROR_146
        1         1         2         1         2         1         1         1
ERROR_147 ERROR_148 ERROR_151 ERROR_152 ERROR_153 ERROR_154 ERROR_158 ERROR_160
        1         1         1         2         2         1         2         3
ERROR_164 ERROR_165 ERROR_167 ERROR_169 ERROR_174 ERROR_180 ERROR_185 ERROR_190
        1         2         3         3         1         1         1         1
ERROR_192 ERROR_194 ERROR_195 ERROR_197 ERROR_199 ERROR_201 ERROR_202 ERROR_203
        2         1         1         1         1         2         1         2
ERROR_204 ERROR_205 ERROR_206 ERROR_208 ERROR_210 ERROR_212 ERROR_213 ERROR_214
        1         2         1         1         1         2         2         2
ERROR_216 ERROR_217 ERROR_219 ERROR_220 ERROR_221 ERROR_222 ERROR_233 ERROR_236
        1         1         2         1         4         1         1         1
ERROR_238 ERROR_241 ERROR_242 ERROR_243 ERROR_244 ERROR_245 ERROR_249 ERROR_250
        1         2         1         1         2         1         1         3
ERROR_251 ERROR_253 ERROR_260 ERROR_261 ERROR_262 ERROR_263 ERROR_264 ERROR_265
        1         1         1         1         1         1         2         1
ERROR_266 ERROR_267 ERROR_269 ERROR_271 ERROR_274 ERROR_275 ERROR_277 ERROR_285
        1         1         1         2         1         2         1         1
ERROR_291 ERROR_295 ERROR_299 ERROR_305 ERROR_307 ERROR_309 ERROR_311 ERROR_313
        1         1         1         2         1         1         1         2
ERROR_314 ERROR_316 ERROR_319 ERROR_320 ERROR_321 ERROR_324 ERROR_325 ERROR_327
        2         1         1         1         1         1         1         1
ERROR_328 ERROR_336 ERROR_338 ERROR_340 ERROR_341 ERROR_342 ERROR_343 ERROR_346
        2         1         1         2         1         1         1         1
ERROR_347 ERROR_352 ERROR_353 ERROR_354 ERROR_356 ERROR_358 ERROR_359 ERROR_361
        1         3         2         2         1         1         1         1
ERROR_362 ERROR_364 ERROR_367 ERROR_368 ERROR_371 ERROR_373 ERROR_376 ERROR_377
        1         1         1         1         2         1         2         1
ERROR_379 ERROR_381 ERROR_382 ERROR_383 ERROR_387 ERROR_389 ERROR_393 ERROR_397
        2         1         2         1         1         1         1         1
ERROR_400 ERROR_403 ERROR_407 ERROR_411 ERROR_414 ERROR_418 ERROR_419 ERROR_421
        2         1         3         3         1         1         1         2
ERROR_422 ERROR_425 ERROR_426 ERROR_427 ERROR_428 ERROR_429 ERROR_431 ERROR_436
        1         1         3         1         1         1         1         1
ERROR_439 ERROR_440 ERROR_441 ERROR_443 ERROR_446 ERROR_447 ERROR_448 ERROR_456
        1         1         1         1         3         2         1         1
ERROR_458 ERROR_462 ERROR_463 ERROR_466 ERROR_470 ERROR_472 ERROR_473 ERROR_476
        2         1         1         1         1         1         1         1
ERROR_478 ERROR_481 ERROR_484 ERROR_485 ERROR_487 ERROR_489 ERROR_493 ERROR_494
        1         1         1         1         1         2         1         2
ERROR_498 ERROR_499 ERROR_503 ERROR_504 ERROR_505 ERROR_515 ERROR_520 ERROR_523
        1         1         1         1         1         1         1         2
ERROR_524 ERROR_529 ERROR_530 ERROR_532 ERROR_534 ERROR_535 ERROR_540 ERROR_541
        1         1         1         2         1         1         1         1
ERROR_544 ERROR_546 ERROR_547 ERROR_548 ERROR_550 ERROR_552 ERROR_556 ERROR_560
        1         1         1         2         1         1         1         1
ERROR_561 ERROR_563 ERROR_564 ERROR_570 ERROR_571 ERROR_573 ERROR_577 ERROR_579
        1         2         1         1         1         2         1         2
ERROR_582 ERROR_583 ERROR_586 ERROR_588 ERROR_590 ERROR_596 ERROR_598 ERROR_602
        1         1         1         2         3         1         1         2
ERROR_603 ERROR_605 ERROR_607 ERROR_610 ERROR_611 ERROR_614 ERROR_616 ERROR_617
        1         1         1         1         3         1         1         1
ERROR_618 ERROR_619 ERROR_623 ERROR_624 ERROR_630 ERROR_636 ERROR_637 ERROR_639
        1         2         1         1         1         1         1         2
ERROR_641 ERROR_643 ERROR_645 ERROR_648 ERROR_650 ERROR_651 ERROR_653 ERROR_662
        2         1         1         2         1         1         1         1
ERROR_664 ERROR_665 ERROR_666 ERROR_669 ERROR_672 ERROR_675 ERROR_677 ERROR_683
        2         2         1         1         1         1         1         1
ERROR_684 ERROR_690 ERROR_693 ERROR_694 ERROR_695 ERROR_698 ERROR_700 ERROR_703
        1         1         1         1         1         1         1         2
ERROR_704 ERROR_710 ERROR_714 ERROR_716 ERROR_720 ERROR_722 ERROR_726 ERROR_729
        1         1         1         2         2         2         1         2
ERROR_732 ERROR_733 ERROR_734 ERROR_742 ERROR_743 ERROR_745 ERROR_746 ERROR_750
        1         1         3         2         2         2         1         1
ERROR_757 ERROR_758 ERROR_759 ERROR_762 ERROR_763 ERROR_764 ERROR_765 ERROR_766
        1         2         1         3         1         2         2         1
ERROR_770 ERROR_771 ERROR_773 ERROR_780 ERROR_781 ERROR_784 ERROR_786 ERROR_791
        1         1         1         3         1         1         1         1
ERROR_793 ERROR_794 ERROR_796 ERROR_797 ERROR_798 ERROR_799 ERROR_803 ERROR_809
        1         1         3         1         2         1         1         1
ERROR_810 ERROR_813 ERROR_817 ERROR_820 ERROR_824 ERROR_825 ERROR_830 ERROR_838
        2         1         2         1         1         1         1         1
ERROR_840 ERROR_841 ERROR_842 ERROR_843 ERROR_846 ERROR_850 ERROR_852 ERROR_854
        1         1         1         1         1         1         1         2
ERROR_857 ERROR_858 ERROR_859 ERROR_861 ERROR_862 ERROR_868 ERROR_873 ERROR_879
        1         2         1         1         1         1         1         1
ERROR_880 ERROR_881 ERROR_884 ERROR_887 ERROR_888 ERROR_889 ERROR_891 ERROR_898
        1         1         1         1         2         2         3         1
ERROR_902 ERROR_904 ERROR_905 ERROR_907 ERROR_908 ERROR_909 ERROR_910 ERROR_911
        2         2         1         1         1         1         1         1
ERROR_912 ERROR_913 ERROR_915 ERROR_917 ERROR_920 ERROR_924 ERROR_925 ERROR_926
        1         1         1         2         1         2         1         1
ERROR_928 ERROR_931 ERROR_934 ERROR_938 ERROR_941 ERROR_946 ERROR_947 ERROR_951
        1         1         2         1         1         1         1         2
ERROR_952 ERROR_955 ERROR_956 ERROR_957 ERROR_960 ERROR_964 ERROR_966 ERROR_967
        1         1         1         1         1         1         1         2
ERROR_969 ERROR_977 ERROR_980 ERROR_984 ERROR_988 ERROR_989 ERROR_993 ERROR_997
        1         1         2         2         1         2         1         1
        F    female    Female    FEMALE  Femenino         M      male      Male
      677       705      4030       690       665       686       710      4034
     MALE Masculino      <NA>
      664       671         0

$Diagnosis

Cardiac Disease            COPD        Diabetes         Healthy    Hypertension
           1473            1828            2861            5419            3764
           <NA>
              0

$Smoking.Status

Current  Former   Never    <NA>
   2994    3909    8442       0

$Physical.Activity.Level

             low       ???     h1gh     High     HIGH      Low      LoW
    1244      621      314      425     2485      941     2233      459
     LOW      lwo moderate Moderate  modrate      N/A     <NA>
     791      324     1038     2809      464     1197        0

$Medication.Type

                  anti hypertensive  Antihypertensive Antihypertensives
              282               756               770              2756
    beta blockers     Beta blockers     beta-blockers           Insulin
              790              2378               777              1491
         insuline               N/A              none              None
              444               309               733              3393
             NONE              <NA>
              466                 0

$Region

                  N/A      rural      Rural semi urban Semi-Urban  Semiurban
       315        330        782       3036        716        649       3351
     urban      Urban      URBAN       <NA>
       766       4919        481          0

$Socioeconomic.Level

  High    Low Middle   <NA>
  2320   6118   6907      0

$Occupation

               Manual labor  Manual Labor           N/A        Office
          329          3066           609           186          3514
office worker        retird       Retired       student       Student
          697           466          3289           449          2740
         <NA>
            0

$Shift

Afternoon   Morning     Night      <NA>
     5295      6300      3750         0

$Season

Autumn Spring Summer Winter   <NA>
  3785   3565   4295   3700      0

$Risk.Category

          ERROR_102 ERROR_103 ERROR_105 ERROR_107 ERROR_110 ERROR_112 ERROR_117
     1326         1         1         1         2         2         1         1
ERROR_119 ERROR_121 ERROR_125 ERROR_127 ERROR_129 ERROR_134 ERROR_140 ERROR_142
        1         1         2         1         2         1         1         1
ERROR_144 ERROR_145 ERROR_146 ERROR_148 ERROR_150 ERROR_152 ERROR_153 ERROR_154
        1         1         1         2         1         1         1         1
ERROR_158 ERROR_159 ERROR_161 ERROR_165 ERROR_166 ERROR_167 ERROR_168 ERROR_169
        1         1         1         1         1         1         1         1
ERROR_171 ERROR_174 ERROR_176 ERROR_181 ERROR_184 ERROR_190 ERROR_191 ERROR_192
        1         2         1         1         1         1         1         2
ERROR_196 ERROR_198 ERROR_199 ERROR_202 ERROR_204 ERROR_207 ERROR_210 ERROR_212
        2         1         1         2         1         1         2         1
ERROR_218 ERROR_220 ERROR_224 ERROR_225 ERROR_226 ERROR_228 ERROR_229 ERROR_236
        4         1         1         1         2         1         1         1
ERROR_237 ERROR_239 ERROR_243 ERROR_244 ERROR_246 ERROR_249 ERROR_251 ERROR_257
        1         3         1         1         3         1         2         1
ERROR_258 ERROR_259 ERROR_261 ERROR_262 ERROR_266 ERROR_268 ERROR_270 ERROR_271
        1         1         1         1         1         1         2         1
ERROR_273 ERROR_275 ERROR_279 ERROR_281 ERROR_285 ERROR_286 ERROR_288 ERROR_291
        1         1         2         1         4         1         1         1
ERROR_292 ERROR_295 ERROR_300 ERROR_302 ERROR_303 ERROR_305 ERROR_306 ERROR_310
        1         3         1         1         1         1         1         2
ERROR_311 ERROR_314 ERROR_315 ERROR_318 ERROR_319 ERROR_321 ERROR_325 ERROR_326
        1         1         1         1         1         1         1         1
ERROR_330 ERROR_332 ERROR_333 ERROR_335 ERROR_337 ERROR_343 ERROR_345 ERROR_347
        2         2         1         1         1         2         1         2
ERROR_351 ERROR_353 ERROR_355 ERROR_358 ERROR_359 ERROR_360 ERROR_364 ERROR_366
        1         1         1         1         1         1         1         2
ERROR_367 ERROR_370 ERROR_376 ERROR_377 ERROR_381 ERROR_382 ERROR_388 ERROR_390
        1         1         2         1         1         1         1         1
ERROR_392 ERROR_394 ERROR_395 ERROR_399 ERROR_400 ERROR_404 ERROR_408 ERROR_409
        1         2         2         1         2         1         1         1
ERROR_410 ERROR_411 ERROR_414 ERROR_418 ERROR_420 ERROR_421 ERROR_422 ERROR_428
        2         1         1         1         1         1         1         1
ERROR_433 ERROR_434 ERROR_435 ERROR_436 ERROR_442 ERROR_444 ERROR_447 ERROR_449
        1         1         1         1         2         1         2         1
ERROR_450 ERROR_452 ERROR_455 ERROR_458 ERROR_462 ERROR_463 ERROR_466 ERROR_467
        1         1         2         1         1         1         1         1
ERROR_470 ERROR_474 ERROR_475 ERROR_477 ERROR_480 ERROR_482 ERROR_483 ERROR_485
        1         1         1         1         1         1         1         1
ERROR_486 ERROR_488 ERROR_489 ERROR_496 ERROR_497 ERROR_498 ERROR_499 ERROR_500
        1         1         1         1         1         1         1         1
ERROR_503 ERROR_504 ERROR_505 ERROR_506 ERROR_513 ERROR_515 ERROR_516 ERROR_517
        2         1         4         1         1         3         1         2
ERROR_518 ERROR_520 ERROR_523 ERROR_525 ERROR_526 ERROR_527 ERROR_528 ERROR_529
        1         1         1         2         2         1         1         1
ERROR_530 ERROR_531 ERROR_533 ERROR_534 ERROR_538 ERROR_539 ERROR_542 ERROR_544
        1         3         1         1         1         1         2         2
ERROR_548 ERROR_549 ERROR_552 ERROR_556 ERROR_557 ERROR_558 ERROR_563 ERROR_564
        1         1         1         1         1         1         1         1
ERROR_566 ERROR_568 ERROR_571 ERROR_573 ERROR_580 ERROR_583 ERROR_584 ERROR_585
        1         1         1         1         1         1         1         1
ERROR_587 ERROR_589 ERROR_594 ERROR_598 ERROR_600 ERROR_601 ERROR_606 ERROR_607
        1         1         1         1         1         1         3         1
ERROR_608 ERROR_610 ERROR_614 ERROR_618 ERROR_622 ERROR_623 ERROR_625 ERROR_626
        1         1         1         1         1         1         1         2
ERROR_628 ERROR_629 ERROR_633 ERROR_641 ERROR_643 ERROR_644 ERROR_645 ERROR_647
        2         2         1         1         1         1         1         3
ERROR_656 ERROR_657 ERROR_658 ERROR_664 ERROR_665 ERROR_671 ERROR_672 ERROR_673
        1         3         1         1         1         1         1         1
ERROR_674 ERROR_675 ERROR_685 ERROR_686 ERROR_689 ERROR_690 ERROR_694 ERROR_696
        1         1         1         2         2         1         1         1
ERROR_697 ERROR_698 ERROR_699 ERROR_700 ERROR_703 ERROR_707 ERROR_708 ERROR_709
        1         1         2         1         2         1         1         1
ERROR_716 ERROR_718 ERROR_720 ERROR_721 ERROR_722 ERROR_725 ERROR_727 ERROR_729
        2         3         1         2         1         2         2         1
ERROR_731 ERROR_733 ERROR_735 ERROR_739 ERROR_744 ERROR_746 ERROR_748 ERROR_749
        2         1         1         1         2         2         3         1
ERROR_754 ERROR_759 ERROR_760 ERROR_765 ERROR_766 ERROR_769 ERROR_770 ERROR_771
        1         2         1         2         1         1         1         1
ERROR_776 ERROR_778 ERROR_779 ERROR_782 ERROR_785 ERROR_787 ERROR_788 ERROR_793
        1         1         2         1         1         1         1         1
ERROR_795 ERROR_796 ERROR_797 ERROR_799 ERROR_801 ERROR_805 ERROR_806 ERROR_809
        2         1         2         1         1         2         1         1
ERROR_811 ERROR_815 ERROR_818 ERROR_820 ERROR_822 ERROR_826 ERROR_827 ERROR_830
        1         1         2         1         2         1         2         2
ERROR_834 ERROR_835 ERROR_844 ERROR_846 ERROR_847 ERROR_853 ERROR_854 ERROR_856
        1         1         1         1         1         1         1         1
ERROR_857 ERROR_858 ERROR_859 ERROR_861 ERROR_862 ERROR_863 ERROR_866 ERROR_868
        2         2         1         1         2         1         1         1
ERROR_869 ERROR_871 ERROR_879 ERROR_884 ERROR_885 ERROR_886 ERROR_887 ERROR_891
        2         2         2         1         1         1         1         1
ERROR_892 ERROR_893 ERROR_894 ERROR_895 ERROR_899 ERROR_900 ERROR_901 ERROR_904
        1         1         1         2         1         1         1         2
ERROR_905 ERROR_907 ERROR_909 ERROR_910 ERROR_913 ERROR_917 ERROR_919 ERROR_920
        1         1         2         1         3         1         1         1
ERROR_923 ERROR_924 ERROR_925 ERROR_926 ERROR_928 ERROR_929 ERROR_931 ERROR_933
        2         1         1         1         1         2         1         2
ERROR_934 ERROR_936 ERROR_940 ERROR_944 ERROR_946 ERROR_947 ERROR_948 ERROR_949
        1         1         1         1         1         1         3         1
ERROR_951 ERROR_954 ERROR_955 ERROR_960 ERROR_961 ERROR_965 ERROR_966 ERROR_967
        1         1         1         1         1         1         1         1
ERROR_969 ERROR_970 ERROR_971 ERROR_972 ERROR_977 ERROR_979 ERROR_980 ERROR_981
        2         2         1         1         1         1         1         1
ERROR_988 ERROR_990 ERROR_992 ERROR_994 ERROR_998 High Risk  Low Risk      <NA>
        1         2         1         1         1      7128      6405         0

## 5) Calcular mínimos y máximos de variables numéricas

In [107]:
# Seleccionar únicamente variables numéricas
variables_numericas <- data[, sapply(data, is.numeric)]

# Ver nombres de variables numéricas
names(variables_numericas)

 [1] "Patient.ID"               "Heart.Rate"
 [3] "Respiratory.Rate"         "Body.Temperature"
 [5] "Oxygen.Saturation"        "Systolic.Blood.Pressure"
 [7] "Diastolic.Blood.Pressure" "Age"
 [9] "Weight..kg."              "Height..m."
[11] "Derived_HRV"              "Derived_Pulse_Pressure"
[13] "Derived_BMI"              "Derived_MAP"
[15] "Glucose"                  "Cholesterol"
[17] "Triglycerides"            "Hemoglobin"
[19] "Creatinine"

In [108]:
# Calcular mínimos y máximos por variable
rangos_observados <- data.frame(
  Variable = names(variables_numericas),
  Minimo = sapply(variables_numericas, min, na.rm = TRUE),
  Maximo = sapply(variables_numericas, max, na.rm = TRUE)
)

rangos_observados

                         Variable                 Minimo       Maximo
Patient.ID               Patient.ID                15.00000000 200008.0000000
Heart.Rate               Heart.Rate                39.00000000    167.0000000
Respiratory.Rate         Respiratory.Rate          12.00000000     43.0000000
Body.Temperature         Body.Temperature          36.00000907     37.4997445
Oxygen.Saturation        Oxygen.Saturation         70.10947987     99.9993445
Systolic.Blood.Pressure  Systolic.Blood.Pressure  110.00000000    188.0000000
Diastolic.Blood.Pressure Diastolic.Blood.Pressure  70.00000000    117.0000000
Age                      Age                       18.00000000     89.0000000
Weight..kg.              Weight..kg.               50.00989612     99.9939482
Height..m.               Height..m.                 1.50000091      1.9999376
Derived_HRV              Derived_HRV                0.05000031      0.4280992
Derived_Pulse_Pressure   Derived_Pulse_Pressure    21.00000000     69.0000000
Derived_BMI              Derived_BMI               12.59367488     44.1861231
Derived_MAP              Derived_MAP               83.33333333    105.6666667
Glucose                  Glucose                   37.90000000    414.4219194
Cholesterol              Cholesterol               91.60000000    373.7000000
Triglycerides            Triglycerides             40.20000000    546.1000000
Hemoglobin               Hemoglobin                 7.70000000     20.9000000
Creatinine               Creatinine                 0.40000000      7.3200000

## 6) Limpieza de datos

In [109]:
# ============================
# CARGA DE LIBRERÍAS
# dplyr facilita manipulación de datasets
# janitor ayuda a limpiar nombres de variables
# ============================

if (!require(dplyr, quietly = TRUE)) {
  suppressMessages(install.packages("dplyr"))
}
library(dplyr)

if (!require(janitor, quietly = TRUE)) {
  suppressMessages(install.packages("janitor"))
}
library(janitor)

In [110]:
library(tidyverse)
library(stringr)

# Estandarización de texto, limpieza de errores y eliminación de NAs
dataset_limpio <- data_filtrado %>%
  # 0. Renombrar PRIMERO todas las columnas al español
  rename(
    id_paciente = Patient.ID,
    frecuencia_cardiaca = Heart.Rate,
    frecuencia_respiratoria = Respiratory.Rate,
    fecha_hora = Timestamp,
    temperatura_corporal = Body.Temperature,
    saturacion_oxigeno = Oxygen.Saturation,
    presion_arterial_sistolica = Systolic.Blood.Pressure,
    presion_arterial_diastolica = Diastolic.Blood.Pressure,
    edad = Age,
    genero = Gender,
    peso_kg = Weight..kg.,
    altura_m = Height..m.,
    vfc_derivada = Derived_HRV,
    presion_pulso_derivada = Derived_Pulse_Pressure,
    imc_derivado = Derived_BMI,
    pam_derivada = Derived_MAP,
    categoria_riesgo = Risk.Category,
    diagnostico = Diagnosis,
    estado_fumador = Smoking.Status,
    nivel_actividad_fisica = Physical.Activity.Level,
    tipo_medicacion = Medication.Type,
    region = Region,
    nivel_socioeconomico = Socioeconomic.Level,
    ocupacion = Occupation,
    turno = Shift,
    estacion = Season,
    glucosa = Glucose,
    colesterol = Cholesterol,
    trigliceridos = Triglycerides,
    hemoglobina = Hemoglobin,
    creatinina = Creatinine
  ) %>%

  # 1. Pasar todo el texto a minúsculas y quitar espacios extra a los lados
  mutate(across(where(is.character), ~ str_to_lower(str_trim(.)))) %>%

  # 1.5. Transformar celdas con "error_" en NA reales en TODAS las variables (incluye categoria_riesgo)
  mutate(across(where(is.character), ~ ifelse(str_detect(., "^error_"), NA, .))) %>%

  # 2. Corregir y unificar categorías específicas
  mutate(
    genero = case_when(
      genero %in% c("female", "femenino", "f") ~ "femenino",
      genero %in% c("male", "masculino", "m")   ~ "masculino",
      TRUE ~ genero
    ),

    nivel_actividad_fisica = case_when(
      nivel_actividad_fisica %in% c("high", "h1gh")        ~ "alto",
      nivel_actividad_fisica %in% c("moderate", "modrate", "") ~ "medio",
      nivel_actividad_fisica %in% c("low", "lwo")          ~ "bajo",
      TRUE ~ nivel_actividad_fisica
    ),

    tipo_medicacion = case_when(
      tipo_medicacion %in% c("beta blockers", "beta-blockers")           ~ "bloqueadores_beta",
      tipo_medicacion %in% c("anti hypertensive", "antihypertensives",
                            "antihypertensive")                          ~ "antihipertensivos",
      tipo_medicacion %in% c("insulin", "insuline")                      ~ "insulina",
      tipo_medicacion %in% c("none") ~ "ninguna",
      TRUE ~ tipo_medicacion
    ),

    region = case_when(
      region %in% c("urban")                      ~ "urbana",
      region %in% c("rural")                      ~ "rural",
      region %in% c("semiurban", "semi-urban", "semi urban")                 ~ "semiurbana",
      TRUE ~ region
    ),

    ocupacion = case_when(
      ocupacion %in% c("student")                ~ "estudiante",
      ocupacion %in% c("office worker", "office") ~ "oficinista",
      ocupacion %in% c("retired", "retird")      ~ "jubilado",
      ocupacion %in% c("manual labor")          ~ "trabajo_manual",
      TRUE ~ ocupacion
    ),

    diagnostico = case_when(
      diagnostico == "healthy"         ~ "sano",
      diagnostico == "hypertension"    ~ "hipertensión",
      diagnostico == "diabetes"        ~ "diabetes",
      diagnostico == "cardiac disease" ~ "enfermedad_cardiaca",
      diagnostico == "copd"            ~ "epoc",
      TRUE ~ diagnostico
    ),

    estado_fumador = case_when(
      estado_fumador == "never"   ~ "nunca",
      estado_fumador == "former"  ~ "ex_fumador",
      estado_fumador == "current" ~ "fumador_actual",
      TRUE ~ estado_fumador
    ),

    nivel_socioeconomico = case_when(
      nivel_socioeconomico == "low"    ~ "bajo",
      nivel_socioeconomico == "middle" ~ "medio",
      nivel_socioeconomico == "high"   ~ "alto",
      TRUE ~ nivel_socioeconomico
    ),

    categoria_riesgo = case_when(
      categoria_riesgo == "high risk" ~ "alto_riesgo",
      categoria_riesgo == "low risk"  ~ "bajo_riesgo",
      TRUE ~ categoria_riesgo
    ),

    turno = case_when(
      turno == "morning"   ~ "mañana",
      turno == "afternoon" ~ "tarde",
      turno == "night"     ~ "noche",
      TRUE ~ turno
    ),

    estacion = case_when(
      estacion == "winter" ~ "invierno",
      estacion == "spring" ~ "primavera",
      estacion == "summer" ~ "verano",
      estacion == "autumn" ~ "otoño",
      TRUE ~ estacion
    )
  ) %>%

  # 3. ACTUALIZACIÓN: Recalcular la cantidad de NAs por fila usando cur_data()
  mutate(cantidad_na = rowSums(is.na(cur_data()))) %>%
  filter(cantidad_na < 7) %>%

  # 4. Eliminar duplicados
  distinct()

# Revisar cuántas filas nos quedaron y un resumen rápido de NAs
cat("Total de registros válidos:", nrow(dataset_limpio), "\n")
table(dataset_limpio$cantidad_na)

Total de registros válidos: 13334

   0    1    2    3    6
9755 3260  302   14    3

In [111]:
table(dataset_limpio$genero, useNA = "always")
table(dataset_limpio$nivel_actividad_fisica, useNA = "always")
table(dataset_limpio$tipo_medicacion, useNA = "always")

 femenino masculino      <NA>
     6665      6667         2

 alto  bajo medio  <NA>
 3347  3835  3744  2408

antihipertensivos bloqueadores_beta          insulina           ninguna
             3724              3429              1682              3992
             <NA>
              507

In [112]:
# ============================
# 5C. TRATAMIENTO DE NA
# Detectar, cuantificar y decidir cómo tratar valores faltantes
# ============================
# ============================
# CONTAR NA POR COLUMNA
# is.na() detecta NA
# colSums() suma cuántos hay en cada variable
# ============================

colSums(is.na(dataset_limpio))

                id_paciente         frecuencia_cardiaca
                          2                           2
    frecuencia_respiratoria                  fecha_hora
                          2                           1
       temperatura_corporal          saturacion_oxigeno
                          1                           1
 presion_arterial_sistolica presion_arterial_diastolica
                          2                           0
                       edad                      genero
                          0                           2
                    peso_kg                    altura_m
                          0                           1
               vfc_derivada      presion_pulso_derivada
                          1                           0
               imc_derivado                pam_derivada
                          1                           0
           categoria_riesgo                 diagnostico
                          2                           0
             estado_fumador      nivel_actividad_fisica
                          0                        2408
            tipo_medicacion                      region
                        507                         557
       nivel_socioeconomico                   ocupacion
                          0                         434
                      turno                    estacion
                          0                           0
                    glucosa                  colesterol
                          0                           0
              trigliceridos                 hemoglobina
                          0                           0
                 creatinina                 cantidad_na
                          0                           0

In [113]:
# ============================
# FILAS CON ALGÚN NA
# if_any revisa si alguna columna cumple condición
# ============================

dataset_limpio %>%
  filter(if_any(everything(), is.na))
dataset_limpio %>%
  filter(if_any(everything(), is.na)) %>%
  nrow()

     id_paciente frecuencia_cardiaca frecuencia_respiratoria
1      15        98                  12
2      25        80                  19
3      46        71                  14
4      59        61                  13
5      80        80                  13
6     174        84                  12
7     346        67                  19
8     402        95                  16
9     522        66                  12
10    568        84                  15
11    613        96                  16
12    675        68                  18
13    874        91                  16
14   1019        94                  16
15   1039        83                  19
16   1129        60                  16
17   1145        61                  15
18   1306        70                  14
19   1327        92                  18
20   1381        76                  19
21   1399        71                  18
22   1553        77                  16
23   1559        79                  14
24   1603        68                  13
25   1609        64                  13
26   1628        67                  14
27   1732        83                  18
28   1784        88                  15
29   1851        71                  19
30   1948        78                  15
⋮    ⋮           ⋮                   ⋮
3550 198596      93                  17
3551 198642      89                  12
3552 198675      76                  17
3553 198724      84                  14
3554 198729      88                  13
3555 198742      68                  18
3556 198764      82                  12
3557 198883      66                  17
3558 198954      94                  19
3559 199002      80                  15
3560 199031      61                  15
3561 199080      97                  15
3562 199088      60                  19
3563 199094      64                  16
3564 199116      92                  13
3565 199168      85                  14
3566 199175      86                  18
3567 199323      76                  19
3568 199334      95                  17
3569 199421      99                  18
3570 199564      93                  15
3571 199629      71                  17
3572 199678      89                  18
3573 199788      99                  19
3574 199821      90                  17
3575 199864      61                  12
3576 199984      65                  14
3577  78633      NA                  NA
3578     NA      69                  14
3579     NA      NA                  NA
     fecha_hora                 temperatura_corporal saturacion_oxigeno
1    2024-07-19 21:39:45.729841 37.26153             98.67484
2    2024-07-19 21:29:45.729841 36.86324             99.51951
3    2024-07-19 21:08:45.729841 37.44475             97.53558
4    2024-07-19 20:55:45.729841 36.53399             97.89955
5    2024-07-19 20:34:45.729841 36.72886             99.16043
6    2024-07-19 19:00:45.729841 37.38135             99.61474
7    2024-07-19 16:08:45.730842 36.15793             97.78303
8    2024-07-19 15:12:45.730842 36.26041             98.14455
9    2024-07-19 13:12:45.730842 37.05059             99.48217
10   2024-07-19 12:26:45.730842 36.67941             97.27663
11   2024-07-19 11:41:45.730842 36.63334             96.97897
12   2024-07-19 10:39:45.730842 36.68391             95.14305
13   2024-07-19 07:20:45.731841 36.70708             96.56932
14   2024-07-19 04:55:45.733846 37.12933             96.42812
15   2024-07-19 04:35:45.733846 36.42526             98.98690
16   2024-07-19 03:05:45.733846 36.71734             97.92785
17   2024-07-19 02:49:45.733846 36.60349             98.60664
18   2024-07-19 00:08:45.734844 36.90831             98.52994
19   2024-07-18 23:47:45.734844 36.09447             98.95140
20   2024-07-18 22:53:45.734844 37.47325             99.63163
21   2024-07-18 22:35:45.734844 36.69275             96.56770
22   2024-07-18 20:01:45.734844 37.05152             97.92219
23   2024-07-18 19:55:45.734844 37.11436             99.61064
24   2024-07-18 19:11:45.734844 36.36631             99.12822
25   2024-07-18 19:05:45.734844 36.83026             97.72185
26   2024-07-18 18:46:45.734844 36.30208             96.18544
27   2024-07-18 17:02:45.734844 36.62825             98.69235
28   2024-07-18 16:10:45.735983 36.17469             99.90391
29   2024-07-18 15:03:45.735983 36.09896             96.66658
30   2024-07-18 13:26:45.735983 36.87920             96.10433
⋮    ⋮                          ⋮                    ⋮
3550 2024-03-03 23:58:46.243948 36.99578             98.94845
3551 2024-03-03 23:12:46.243948 36.32591             96.08772
3552 2024-03-03 22:39:46.243948 37.29102             99.34945
3553 2024-03-03 21:50:46.243948 37.15303             97.71399
3554 2024-03-03 21:45:46.243948 37.32660             99.81713
3555 2024-03-03 21:32:46.243948 36.58396             99.30741
3556 2024-03-03 21:10:46.243948 37.48439             99.43559
3557 2024-03-03 19:11:46.243948 36.51082             96.36788
3558 2024-03-03 18:00:46.243948 36.92346             99.44376
3559 2024-03-03 17:12:46.243948 36.30605             95.15321
3560 2024-03-03 16:43:46.243948 36.01893             97.25028
3561 2024-03-03 15:54:46.243948 37.36873             96.65223
3562 2024-03-03 15:46:46.243948 36.06411             98.96775
3563 2024-03-03 15:40:46.243948 36.77881             99.03703
3564 2024-03-03 15:18:46.244949 37.14187             99.84610
3565 2024-03-03 14:26:46.244949 37.46114             97.13528
3566 2024-03-03 14:19:46.244949 37.29436             95.40539
3567 2024-03-03 11:51:46.244949 36.93410             97.36797
3568 2024-03-03 11:40:46.244949 37.05482             98.03679
3569 2024-03-03 10:13:46.244949 36.74675             97.76180
3570 2024-03-03 07:50:46.244949 36.44251             99.03504
3571 2024-03-03 06:45:46.245949 36.90065             95.19717
3572 2024-03-03 05:56:46.245949 37.34913             96.72439
3573 2024-03-03 04:06:46.245949 36.35636             95.70487
3574 2024-03-03 03:33:46.245949 37.39991             99.18685
3575 2024-03-03 02:50:46.245949 36.29098             95.45625
3576 2024-03-03 00:50:46.246950 36.34425             99.70034
3577 2024-05-26 07:21:45.929006 36.61633             95.30559
3578 2024-07-04 22:39:45.784855       NA                   NA
3579 NA                         36.12623             95.21659
     presion_arterial_sistolica presion_arterial_diastolica edad genero    ⋯
1    127                        87                          89   femenino  ⋯
2    117                        77                          62   masculino ⋯
3    126                        84                          77   masculino ⋯
4    139                        85                          42   masculino ⋯
5    128                        79                          61   femenino  ⋯
6    115                        88                          26   masculino ⋯
7    115                        80                          75   masculino ⋯
8    125                        72                          89   femenino  ⋯
9    136                        88                          76   masculino ⋯
10   133                        75                          54   femenino  ⋯
11   121                        82                          27   masculino ⋯
12   136                        81                          65   femenino  ⋯
13   122                        74                          41   masculino ⋯
14   120                        75                          60   masculino ⋯
15   139                        82                          59   femenino  ⋯
16   127                        86                          22   masculino ⋯
17   112                        79                          59   femenino  ⋯
18   122                        87                          68   femenino  ⋯
19   134                        74                          69   femenino  ⋯
20   134                        84                          57   masculino ⋯
21   135                        89                          24   masculino ⋯
22   119                        74                          29   masculino ⋯
23   137                        88                          50   femenino  ⋯
24   116                        73                          44   masculino ⋯
25   111                        81                          24   masculino ⋯
26   131                        77                          70   masculino ⋯
27   125                        71                          44   masculino ⋯
28   134                        77                          89   masculino ⋯
29   123                        89                          21   masculino ⋯
30   113                        88                          31   femenino  ⋯
⋮    ⋮                          ⋮                           ⋮    ⋮         ⋱
3550 113                        83                          58   masculino ⋯
3551 133                        71                          26   masculino ⋯
3552 121                        86                          55   femenino  ⋯
3553 133                        88                          81   masculino ⋯
3554 139                        78                          87   masculino ⋯
3555 115                        71                          51   masculino ⋯
3556 110                        71                          38   masculino ⋯
3557 113                        75                          74   femenino  ⋯
3558 117                        73                          62   masculino ⋯
3559 129                        79                          45   femenino  ⋯
3560 111                        87                          27   masculino ⋯
3561 110                        72                          39   femenino  ⋯
3562 123                        76                          59   masculino ⋯
3563 135                        74                          54   masculino ⋯
3564 114                        72                          88   femenino  ⋯
3565 124                        73                          76   femenino  ⋯
3566 139                        73                          52   masculino ⋯
3567 131                        83                          69   femenino  ⋯
3568 122                        88                          79   femenino  ⋯
3569 126                        85                          51   masculino ⋯
3570 110                        89                          49   masculino ⋯
3571 133                        82                          37   masculino ⋯
3572 110                        80                          87   masculino ⋯
3573 136                        71                          75   femenino  ⋯
3574 129                        78                          58   masculino ⋯
3575 122                        84                          83   femenino  ⋯
3576 115                        72                          48   masculino ⋯
3577  NA                        86                          69   NA        ⋯
3578  NA                        80                          73   NA        ⋯
3579 132                        82                          65   masculino ⋯
     nivel_socioeconomico ocupacion      turno  estacion  glucosa colesterol
1    bajo                 oficinista     mañana invierno  114.2   210.8
2    bajo                 NA             tarde  primavera 111.8   266.1
3    medio                estudiante     mañana invierno  103.1   173.0
4    medio                oficinista     tarde  invierno  116.3   213.9
5    medio                trabajo_manual tarde  verano    207.7   203.0
6    medio                NA             mañana verano    115.5   175.3
7    medio                oficinista     tarde  verano     87.2   134.9
8    medio                trabajo_manual mañana verano    111.5   212.1
9    alto                 oficinista     tarde  verano     89.3   307.3
10   bajo                 oficinista     noche  verano    193.9   123.1
11   bajo                 trabajo_manual mañana invierno  107.1   179.1
12   alto                 estudiante     mañana verano    117.7   256.2
13   medio                jubilado       mañana otoño     117.2   218.1
14   bajo                 NA             mañana verano    100.1   191.3
15   medio                trabajo_manual tarde  verano    103.4   189.2
16   bajo                 oficinista     mañana otoño     147.8   171.2
17   alto                 trabajo_manual mañana verano    126.3   263.4
18   medio                jubilado       tarde  verano    121.3   291.0
19   medio                jubilado       mañana otoño      98.2   229.4
20   bajo                 estudiante     noche  otoño     110.8   269.6
21   medio                estudiante     mañana otoño     105.5   172.5
22   medio                jubilado       noche  verano    105.2   187.5
23   bajo                 estudiante     noche  primavera 109.1   163.5
24   medio                oficinista     tarde  verano     91.2   226.9
25   medio                jubilado       mañana invierno  105.2   209.8
26   medio                oficinista     noche  invierno   89.9   205.7
27   medio                oficinista     mañana primavera 136.9   214.9
28   bajo                 jubilado       noche  verano    108.6   171.8
29   bajo                 estudiante     tarde  primavera 156.9   154.9
30   medio                NA             noche  verano    204.6   181.9
⋮    ⋮                    ⋮              ⋮      ⋮         ⋮       ⋮
3550 bajo                 jubilado       mañana verano     87.1   192.8
3551 bajo                 trabajo_manual mañana verano    241.8   248.2
3552 bajo                 oficinista     noche  otoño     246.9   182.3
3553 bajo                 trabajo_manual tarde  verano     97.5   206.6
3554 medio                oficinista     tarde  verano    165.2   207.4
3555 medio                estudiante     mañana verano     88.5   196.4
3556 bajo                 trabajo_manual mañana primavera 137.3   183.3
3557 medio                NA             mañana verano    104.8   151.8
3558 medio                trabajo_manual noche  otoño      79.5   289.7
3559 medio                trabajo_manual mañana otoño     104.7   237.0
3560 bajo                 jubilado       tarde  verano     78.5   214.4
3561 alto                 jubilado       mañana otoño     126.7   222.3
3562 alto                 jubilado       mañana verano     69.9   209.2
3563 medio                estudiante     mañana invierno  118.5   262.0
3564 bajo                 NA             tarde  primavera 117.1   202.0
3565 alto                 NA             tarde  primavera 122.6   162.3
3566 bajo                 oficinista     tarde  otoño     101.2   209.4
3567 medio                oficinista     mañana invierno   80.1   220.7
3568 medio                estudiante     mañana primavera 114.1   266.6
3569 medio                trabajo_manual mañana otoño      94.4   218.5
3570 medio                oficinista     tarde  verano    102.0   220.3
3571 medio                trabajo_manual noche  otoño      81.8   256.0
3572 medio                trabajo_manual mañana invierno  134.9   185.6
3573 medio                NA             noche  invierno   91.7   171.9
3574 medio                jubilado       mañana otoño     140.8   213.2
3575 bajo                 oficinista     mañana invierno  181.0   152.8
3576 bajo                 oficinista     mañana primavera  84.7   172.6
3577 bajo                 jubilado       mañana invierno  130.5   254.0
3578 bajo                 trabajo_manual noche  invierno  103.9   217.2
3579 medio                jubilado       mañana verano     97.9   261.4
     trigliceridos hemoglobina creatinina cantidad_na
1    188.9         13.8        1.70       1
2    162.6         15.0        0.96       1
3    346.4         15.9        4.04       1
4    162.5         16.8        1.26       1
5    265.1         11.5        0.60       1
6     97.7         15.4        0.84       1
7    129.7         16.5        0.76       1
8    104.3         15.5        1.56       1
9    277.1         13.2        1.26       1
10   216.9         15.3        1.07       1
11   261.5         14.4        1.28       1
12   310.7         14.6        1.32       1
13   130.8         14.1        0.98       1
14   213.4         14.1        1.65       1
15   133.4         13.2        0.84       1
16   186.6         10.1        0.91       1
17   198.4         14.8        1.59       1
18   213.8         10.6        1.46       1
19   177.2         16.5        1.62       1
20   325.6         16.2        1.26       1
21   192.6         15.6        1.15       1
22   217.8         14.0        1.31       1
23   155.7         12.2        1.28       1
24   116.6         13.3        0.86       1
25    56.8         13.1        1.06       1
26   201.4         15.7        1.11       2
27   201.9         13.1        1.63       1
28   131.8         13.0        1.11       1
29   212.7         12.8        0.78       2
30   177.3         13.0        0.94       1
⋮    ⋮             ⋮           ⋮          ⋮
3550 158.4         14.9        1.46       1
3551 219.8         12.5        0.82       1
3552 248.0         11.1        0.85       1
3553 164.1         13.6        1.20       1
3554 281.4         12.6        1.23       1
3555 116.3         14.4        1.17       1
3556 116.0         15.4        0.82       1
3557 117.5         14.2        1.57       1
3558 248.9         13.2        1.07       1
3559 154.2         18.2        1.02       1
3560 100.7         16.1        0.92       1
3561 222.5         14.3        1.09       1
3562 200.3         14.3        0.69       1
3563 306.4         13.4        1.45       1
3564 221.8         13.2        1.50       1
3565 193.2         13.9        1.14       1
3566 124.6         13.4        1.31       1
3567 176.9         12.4        4.72       1
3568 256.7         12.3        1.47       1
3569 157.6          8.5        1.49       1
3570 205.0         17.4        1.13       2
3571 410.1         15.0        1.21       1
3572 192.6         14.8        1.23       1
3573 151.7         13.3        1.44       2
3574 259.9         12.1        0.62       1
3575 273.5         17.0        0.83       1
3576 192.9         16.5        1.10       1
3577 223.5         13.3        0.87       6
3578 197.9         13.2        1.00       6
3579 237.8         15.3        1.12       6

[1] 3579

In [114]:
# Eliminar filas completamente vacías
# ============================
# ELIMINAR FILAS COMPLETAMENTE VACÍAS
# Conserva solo filas que tengan al menos un dato
# ============================

# ============================
# ELIMINAR FILAS CON ALGÚN NA
# Conserva solo filas completas
# ============================

dataset_limpio1 <- dataset_limpio %>%
  filter(!if_any(everything(), is.na))
nrow(dataset_limpio1)

[1] 9755

Observación:
pocos NA → eliminar filas
muchos NA → imputar o conservarlos y trabajar con ellos ignorando na
NA informativos → conservar
cuidado con eliminar na sin haber observado la estructura del dataset    
Eliminar filas con cualquier NA puede ser muy agresivo.

Ejemplo:  

fila con 33 variables correctas  
1 sola variable faltante  → se elimina igual.

In [115]:
# ============================
# CONTAR DUPLICADOS EXACTOS
# duplicated() marca filas repetidas completas
# ============================

sum(duplicated(dataset_limpio))

# ============================
# ELIMINAR DUPLICADOS EXACTOS
# distinct() conserva una sola copia
# ============================

dataset_limpio <- dataset_limpio %>%
  mutate(fecha_hora = ymd_hms(fecha_hora)) %>%   # Convertir antes de distinct
  distinct(id_paciente, fecha_hora, .keep_all = TRUE)  # Elimina solo duplicados exactos por paciente+fecha

nrow(dataset_limpio)
n_distinct(dataset_limpio$id_paciente)

[1] 0

[1] 13334

[1] 13333

In [116]:
dataset_limpio %>%
  group_by(id_paciente, fecha_hora) %>%
  filter(n() > 1)

Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”

     id_paciente frecuencia_cardiaca frecuencia_respiratoria fecha_hora
     temperatura_corporal saturacion_oxigeno presion_arterial_sistolica
     presion_arterial_diastolica edad genero ⋯ nivel_socioeconomico ocupacion
     turno estacion glucosa colesterol trigliceridos hemoglobina creatinina
     cantidad_na

### PREPARACIÓN DE VARIABLES NUMÉRICAS

In [117]:
# ============================
# PREPARACIÓN DE VARIABLES NUMÉRICAS
# Convertir variables a numéricas y formatear resultados
# ============================

In [118]:
summary(dataset_limpio)

  id_paciente     frecuencia_cardiaca frecuencia_respiratoria
 Min.   :    15   Min.   : 39.00      Min.   :12.00
 1st Qu.: 50221   1st Qu.: 70.00      1st Qu.:13.00
 Median : 99566   Median : 80.00      Median :16.00
 Mean   :100146   Mean   : 79.53      Mean   :15.51
 3rd Qu.:150529   3rd Qu.: 90.00      3rd Qu.:18.00
 Max.   :200008   Max.   :167.00      Max.   :43.00
 NAs    :2        NAs    :2           NAs    :2
   fecha_hora                  temperatura_corporal saturacion_oxigeno
 Min.   :2024-03-03 00:26:46   Min.   :36.00        Min.   : 70.11
 1st Qu.:2024-04-06 09:13:46   1st Qu.:36.37        1st Qu.: 96.27
 Median :2024-05-11 18:33:45   Median :36.75        Median : 97.52
 Mean   :2024-05-11 08:54:56   Mean   :36.75        Mean   : 97.49
 3rd Qu.:2024-06-15 01:06:45   3rd Qu.:37.12        3rd Qu.: 98.75
 Max.   :2024-07-19 21:39:45   Max.   :37.50        Max.   :100.00
 NAs    :1                     NAs    :1            NAs    :1
 presion_arterial_sistolica presion_arterial_diastolica      edad
 Min.   :110.0              Min.   : 70.00              Min.   :18.00
 1st Qu.:117.0              1st Qu.: 74.00              1st Qu.:36.00
 Median :124.0              Median : 79.00              Median :53.00
 Mean   :124.5              Mean   : 79.51              Mean   :53.54
 3rd Qu.:132.0              3rd Qu.: 84.00              3rd Qu.:71.00
 Max.   :188.0              Max.   :117.00              Max.   :89.00
 NAs    :2
       genero         peso_kg         altura_m      vfc_derivada
 Length   :13334   Min.   :50.01   Min.   :1.500   Min.   :0.05000
 N.unique :    2   1st Qu.:62.40   1st Qu.:1.626   1st Qu.:0.07510
 N.blank  :    0   Median :74.98   Median :1.752   Median :0.09993
 Min.nchar:    8   Mean   :75.00   Mean   :1.751   Mean   :0.10011
 Max.nchar:    9   3rd Qu.:87.69   3rd Qu.:1.875   3rd Qu.:0.12505
 NAs      :    2   Max.   :99.99   Max.   :2.000   Max.   :0.42810
                                   NAs    :1       NAs    :1
 presion_pulso_derivada  imc_derivado    pam_derivada     categoria_riesgo
 Min.   :21.00          Min.   :12.59   Min.   : 83.33   Length   :13334
 1st Qu.:38.00          1st Qu.:20.17   1st Qu.: 91.00   N.unique :    2
 Median :45.00          Median :24.31   Median : 94.33   N.blank  :    0
 Mean   :44.98          Mean   :24.96   Mean   : 94.48   Min.nchar:   11
 3rd Qu.:53.00          3rd Qu.:29.19   3rd Qu.: 98.00   Max.nchar:   11
 Max.   :69.00          Max.   :44.19   Max.   :105.67   NAs      :    2
                        NAs    :1
    diagnostico      estado_fumador  nivel_actividad_fisica  tipo_medicacion
 Length   :13334   Length   :13334   Length   :13334        Length   :13334
 N.unique :    5   N.unique :    3   N.unique :    3        N.unique :    4
 N.blank  :    0   N.blank  :    0   N.blank  :    0        N.blank  :    0
 Min.nchar:    4   Min.nchar:    5   Min.nchar:    4        Min.nchar:    7
 Max.nchar:   19   Max.nchar:   14   Max.nchar:    5        Max.nchar:   17
                                     NAs      : 2408        NAs      :  507

       region      nivel_socioeconomico     ocupacion           turno
 Length   :13334   Length   :13334      Length   :13334   Length   :13334
 N.unique :    3   N.unique :    3      N.unique :    4   N.unique :    3
 N.blank  :    0   N.blank  :    0      N.blank  :    0   N.blank  :    0
 Min.nchar:    5   Min.nchar:    4      Min.nchar:    8   Min.nchar:    5
 Max.nchar:   10   Max.nchar:    5      Max.nchar:   14   Max.nchar:    6
 NAs      :  557                        NAs      :  434

      estacion        glucosa        colesterol    trigliceridos
 Length   :13334   Min.   : 43.5   Min.   : 91.6   Min.   : 40.2
 N.unique :    4   1st Qu.: 92.3   1st Qu.:183.7   1st Qu.:145.2
 N.blank  :    0   Median :104.2   Median :209.8   Median :186.7
 Min.nchar:    5   Mean   :114.8   Mean   :213.1   Mean   :198.7
 Max.nchar:    9   3rd Qu.:120.4   3rd Qu.:239.2   3rd Qu.:247.1
                   Max.   :381.2   Max.   :373.7   Max.   :546.1

  hemoglobina      creatinina     cantidad_na
 Min.   : 7.70   Min.   :0.400   Min.   :0.0000
 1st Qu.:13.20   1st Qu.:1.000   1st Qu.:0.0000
 Median :14.30   Median :1.210   Median :0.0000
 Mean   :14.18   Mean   :1.273   Mean   :0.2943
 3rd Qu.:15.30   3rd Qu.:1.450   3rd Qu.:1.0000
 Max.   :20.90   Max.   :7.320   Max.   :6.0000

In [119]:

# ============================
# CONVERTIR CHARACTER A NUMÉRICO
# as.numeric() transforma texto en números
# Útil cuando R leyó números como character
# ============================

class(dataset_limpio$glucosa)

dataset_limpio <- dataset_limpio %>%
  mutate(
    glucosa = as.numeric(glucosa)
  )

class(dataset_limpio$glucosa)

# ============================
# CONVERTIR VARIAS VARIABLES A NUMÉRICAS
# across() aplica la misma transformación
# ============================

dataset_limpio <- dataset_limpio %>%
  mutate(
    across(
      c(glucosa, colesterol, trigliceridos, hemoglobina, creatinina),
      as.numeric
    )
  )

[1] "numeric"

[1] "numeric"

In [120]:
# ============================
# DESACTIVAR NOTACIÓN CIENTÍFICA
# scipen alto fuerza formato decimal
# ============================

options(scipen = 999)

In [121]:
# ============================
# REDONDEAR A 2 DECIMALES TODAS LAS VARIABLES NUMÉRICAS
# round(x, 2)
# ============================

dataset_limpio <- dataset_limpio %>%
  mutate(
    across(
      where(is.numeric),
      ~ round(., 2)
    )
  )

In [122]:
summary(dataset_limpio)

  id_paciente     frecuencia_cardiaca frecuencia_respiratoria
 Min.   :    15   Min.   : 39.00      Min.   :12.00
 1st Qu.: 50221   1st Qu.: 70.00      1st Qu.:13.00
 Median : 99566   Median : 80.00      Median :16.00
 Mean   :100146   Mean   : 79.53      Mean   :15.51
 3rd Qu.:150529   3rd Qu.: 90.00      3rd Qu.:18.00
 Max.   :200008   Max.   :167.00      Max.   :43.00
 NAs    :2        NAs    :2           NAs    :2
   fecha_hora                  temperatura_corporal saturacion_oxigeno
 Min.   :2024-03-03 00:26:46   Min.   :36.00        Min.   : 70.11
 1st Qu.:2024-04-06 09:13:46   1st Qu.:36.37        1st Qu.: 96.27
 Median :2024-05-11 18:33:45   Median :36.75        Median : 97.52
 Mean   :2024-05-11 08:54:56   Mean   :36.75        Mean   : 97.49
 3rd Qu.:2024-06-15 01:06:45   3rd Qu.:37.12        3rd Qu.: 98.75
 Max.   :2024-07-19 21:39:45   Max.   :37.50        Max.   :100.00
 NAs    :1                     NAs    :1            NAs    :1
 presion_arterial_sistolica presion_arterial_diastolica      edad
 Min.   :110.0              Min.   : 70.00              Min.   :18.00
 1st Qu.:117.0              1st Qu.: 74.00              1st Qu.:36.00
 Median :124.0              Median : 79.00              Median :53.00
 Mean   :124.5              Mean   : 79.51              Mean   :53.54
 3rd Qu.:132.0              3rd Qu.: 84.00              3rd Qu.:71.00
 Max.   :188.0              Max.   :117.00              Max.   :89.00
 NAs    :2
       genero         peso_kg         altura_m      vfc_derivada
 Length   :13334   Min.   :50.01   Min.   :1.500   Min.   :0.0500
 N.unique :    2   1st Qu.:62.40   1st Qu.:1.630   1st Qu.:0.0800
 N.blank  :    0   Median :74.98   Median :1.750   Median :0.1000
 Min.nchar:    8   Mean   :75.00   Mean   :1.751   Mean   :0.1001
 Max.nchar:    9   3rd Qu.:87.69   3rd Qu.:1.880   3rd Qu.:0.1300
 NAs      :    2   Max.   :99.99   Max.   :2.000   Max.   :0.4300
                                   NAs    :1       NAs    :1
 presion_pulso_derivada  imc_derivado    pam_derivada     categoria_riesgo
 Min.   :21.00          Min.   :12.59   Min.   : 83.33   Length   :13334
 1st Qu.:38.00          1st Qu.:20.17   1st Qu.: 91.00   N.unique :    2
 Median :45.00          Median :24.31   Median : 94.33   N.blank  :    0
 Mean   :44.98          Mean   :24.96   Mean   : 94.48   Min.nchar:   11
 3rd Qu.:53.00          3rd Qu.:29.19   3rd Qu.: 98.00   Max.nchar:   11
 Max.   :69.00          Max.   :44.19   Max.   :105.67   NAs      :    2
                        NAs    :1
    diagnostico      estado_fumador  nivel_actividad_fisica  tipo_medicacion
 Length   :13334   Length   :13334   Length   :13334        Length   :13334
 N.unique :    5   N.unique :    3   N.unique :    3        N.unique :    4
 N.blank  :    0   N.blank  :    0   N.blank  :    0        N.blank  :    0
 Min.nchar:    4   Min.nchar:    5   Min.nchar:    4        Min.nchar:    7
 Max.nchar:   19   Max.nchar:   14   Max.nchar:    5        Max.nchar:   17
                                     NAs      : 2408        NAs      :  507

       region      nivel_socioeconomico     ocupacion           turno
 Length   :13334   Length   :13334      Length   :13334   Length   :13334
 N.unique :    3   N.unique :    3      N.unique :    4   N.unique :    3
 N.blank  :    0   N.blank  :    0      N.blank  :    0   N.blank  :    0
 Min.nchar:    5   Min.nchar:    4      Min.nchar:    8   Min.nchar:    5
 Max.nchar:   10   Max.nchar:    5      Max.nchar:   14   Max.nchar:    6
 NAs      :  557                        NAs      :  434

      estacion        glucosa        colesterol    trigliceridos
 Length   :13334   Min.   : 43.5   Min.   : 91.6   Min.   : 40.2
 N.unique :    4   1st Qu.: 92.3   1st Qu.:183.7   1st Qu.:145.2
 N.blank  :    0   Median :104.2   Median :209.8   Median :186.7
 Min.nchar:    5   Mean   :114.8   Mean   :213.1   Mean   :198.7
 Max.nchar:    9   3rd Qu.:120.4   3rd Qu.:239.2   3rd Qu.:247.1
                   Max.   :381.2   Max.   :373.7   Max.   :546.1

  hemoglobina      creatinina     cantidad_na
 Min.   : 7.70   Min.   :0.400   Min.   :0.0000
 1st Qu.:13.20   1st Qu.:1.000   1st Qu.:0.0000
 Median :14.30   Median :1.210   Median :0.0000
 Mean   :14.18   Mean   :1.273   Mean   :0.2943
 3rd Qu.:15.30   3rd Qu.:1.450   3rd Qu.:1.0000
 Max.   :20.90   Max.   :7.320   Max.   :6.0000

In [123]:
# ============================
# VALIDACIÓN CLÍNICA: HEART RATE
# Frecuencia cardíaca (bpm)
# Rango clínicamente plausible: 30 - 220
# ============================
dataset_limpio %>%
  summarise(
    minimo = min(frecuencia_cardiaca, na.rm = TRUE),
    maximo = max(frecuencia_cardiaca, na.rm = TRUE)
  )

  # ============================
# IDENTIFICAR OUTLIERS CLÍNICOS
# Valores fuera del rango aceptable
# ============================

outliers_hr <- dataset_limpio %>%
  filter(frecuencia_cardiaca < 30 | frecuencia_cardiaca > 220)

outliers_hr

# ============================
# ELIMINAR OUTLIERS DE HEART RATE
# Conserva solo valores dentro del rango clínico
# ============================

dataset_limpio <- dataset_limpio %>%
  filter(frecuencia_cardiaca >= 30,
         frecuencia_cardiaca <= 220)

  minimo maximo
1 39     167

Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
“number of rows of result is not a multiple of vector length (arg 2)”

     id_paciente frecuencia_cardiaca frecuencia_respiratoria fecha_hora
     temperatura_corporal saturacion_oxigeno presion_arterial_sistolica
     presion_arterial_diastolica edad genero ⋯ nivel_socioeconomico ocupacion
     turno estacion glucosa colesterol trigliceridos hemoglobina creatinina
     cantidad_na

In [124]:
# Cargamos lubridate para manejar fechas fácilmente
library(lubridate)

# Ajuste de tipos de datos sobre nuestro dataset_limpio
dataset_limpio <- dataset_limpio %>%
  # A. Convertir la columna de texto a formato fecha-hora real
  mutate(
    fecha_hora = ymd_hms(fecha_hora)
  ) %>%

  # B. Convertir variables cualitativas a "Factores" (categorías)
  mutate(
    across(
      c(genero, categoria_riesgo, diagnostico, estado_fumador,
        nivel_actividad_fisica, tipo_medicacion, region,
        nivel_socioeconomico, ocupacion, turno, estacion),
      as.factor
    )
  )

# Verificamos cómo cambió la estructura
str(dataset_limpio %>% select(fecha_hora, genero, region))

'data.frame':	13332 obs. of  3 variables:
 $ fecha_hora: POSIXct, format: "2024-07-19 21:39:45" "2024-07-19 21:29:45" ...
 $ genero    : Factor w/ 2 levels "femenino","masculino": 1 2 2 1 2 1 2 1 1 2 ...
 $ region    : Factor w/ 3 levels "rural","semiurbana",..: 3 1 3 2 NA 2 1 3 2 3 ...

In [125]:
# ==========================================
# PARTE 6 - INGENIERÍA DE VARIABLES
# ==========================================
# ==========================================
# VARIABLE DERIVADA 1: Indicador de Anemia
# ==========================================

dataset_limpio <- dataset_limpio %>%
  mutate(
    indicador_anemia = case_when(
      genero == "femenino" & hemoglobina < 12 ~ 1,
      genero == "masculino" & hemoglobina < 13 ~ 1,
      TRUE ~ 0
    )
  )
# ==========================================
# VARIABLE DERIVADA 2: Indicador de Taquicardia
# ==========================================

dataset_limpio <- dataset_limpio %>%
  mutate(
    indicador_taquicardia = as.numeric(frecuencia_cardiaca >= 100)
  )
  # ==========================================
# VARIABLE DERIVADA 3: Colesterol Alto
# ==========================================

dataset_limpio <- dataset_limpio %>%
  mutate(
    colesterol_alto = as.numeric(colesterol >= 240)
  )
  dataset_limpio %>% select(indicador_anemia, indicador_taquicardia, colesterol_alto) %>% head(10)

   indicador_anemia indicador_taquicardia colesterol_alto
1  0                0                     0
2  0                0                     1
3  0                0                     0
4  0                0                     0
5  0                0                     0
6  0                0                     0
7  0                0                     0
8  1                0                     0
9  0                0                     0
10 0                0                     1

In [126]:
# ==========================================
# RECOLECCIÓN DE RESULTADOS PARA LA GUÍA
# ==========================================

# 1. Dimensiones finales
cat("=== DIMENSIONES FINALES ===\n")
cat("Filas:", nrow(dataset_limpio), "\n")
cat("Columnas:", ncol(dataset_limpio), "\n\n")

# 2. Pacientes únicos
cat("=== PACIENTES ÚNICOS ===\n")
cat("Pacientes únicos:", n_distinct(dataset_limpio$id_paciente), "\n\n")

# 3. NAs por columna (solo las que tienen)
cat("=== NAs POR COLUMNA ===\n")
na_count <- colSums(is.na(dataset_limpio))
print(na_count[na_count > 0])
cat("\n")

# 4. Rangos de variables numéricas (para validación clínica)
cat("=== RANGOS DE VARIABLES NUMÉRICAS ===\n")
numericas <- dataset_limpio %>% select(where(is.numeric))
rangos <- data.frame(
  Variable = names(numericas),
  Min = sapply(numericas, min, na.rm = TRUE),
  Max = sapply(numericas, max, na.rm = TRUE)
)
print(rangos)
cat("\n")

# 5. Distribución de variables categóricas clave
cat("=== CATEGORÍA DE RIESGO ===\n")
print(table(dataset_limpio$categoria_riesgo, useNA = "always"))
cat("\n")

cat("=== DIAGNÓSTICO ===\n")
print(table(dataset_limpio$diagnostico, useNA = "always"))
cat("\n")

cat("=== GÉNERO ===\n")
print(table(dataset_limpio$genero, useNA = "always"))
cat("\n")

cat("=== ESTADO FUMADOR ===\n")
print(table(dataset_limpio$estado_fumador, useNA = "always"))
cat("\n")

cat("=== NIVEL DE ACTIVIDAD FÍSICA ===\n")
print(table(dataset_limpio$nivel_actividad_fisica, useNA = "always"))

=== DIMENSIONES FINALES ===
Filas: 13332
Columnas: 35

=== PACIENTES ÚNICOS ===
Pacientes únicos: 13332

=== NAs POR COLUMNA ===
               id_paciente       temperatura_corporal
                         1                          1
        saturacion_oxigeno presion_arterial_sistolica
                         1                          1
                    genero           categoria_riesgo
                         1                          1
    nivel_actividad_fisica            tipo_medicacion
                      2408                        507
                    region                  ocupacion
                       557                        434

=== RANGOS DE VARIABLES NUMÉRICAS ===
                                               Variable    Min       Max
id_paciente                                 id_paciente  15.00 200008.00
frecuencia_cardiaca                 frecuencia_cardiaca  39.00    167.00
frecuencia_respiratoria         frecuencia_respiratoria  12.00     43.00
temperatura_corporal               temperatura_corporal  36.00     37.50
saturacion_oxigeno                   saturacion_oxigeno  70.11    100.00
presion_arterial_sistolica   presion_arterial_sistolica 110.00    188.00
presion_arterial_diastolica presion_arterial_diastolica  70.00    117.00
edad                                               edad  18.00     89.00
peso_kg                                         peso_kg  50.01     99.99
altura_m                                       altura_m   1.50      2.00
vfc_derivada                               vfc_derivada   0.05      0.43
presion_pulso_derivada           presion_pulso_derivada  21.00     69.00
imc_derivado                               imc_derivado  12.59     44.19
pam_derivada                               pam_derivada  83.33    105.67
glucosa                                         glucosa  43.50    381.23
colesterol                                   colesterol  91.60    373.70
trigliceridos                             trigliceridos  40.20    546.10
hemoglobina                                 hemoglobina   7.70     20.90
creatinina                                   creatinina   0.40      7.32
cantidad_na                                 cantidad_na   0.00      6.00
indicador_anemia                       indicador_anemia   0.00      1.00
indicador_taquicardia             indicador_taquicardia   0.00      1.00
colesterol_alto                         colesterol_alto   0.00      1.00

=== CATEGORÍA DE RIESGO ===

alto_riesgo bajo_riesgo        <NA>
       7012        6319           1

=== DIAGNÓSTICO ===

           diabetes enfermedad_cardiaca                epoc        hipertensión
               2487                1300                1557                3290
               sano                <NA>
               4698                   0

=== GÉNERO ===

 femenino masculino      <NA>
     6665      6666         1

=== ESTADO FUMADOR ===

    ex_fumador fumador_actual          nunca           <NA>
          3392           2600           7340              0

=== NIVEL DE ACTIVIDAD FÍSICA ===

 alto  bajo medio  <NA>
 3347  3835  3742  2408

# Sección 3 — Exportar archivos / Generar subconjuntos

In [127]:
# ==========================================
# VARIABLE DERIVADA 4: Categoria de creatinina
# Clasifica la funcion renal segun la creatinina serica.
# Normal < 1,00 | Leve 1,00-1,49 | Moderada 1,50-2,99 | Severa >= 3,00
# ==========================================

dataset_limpio <- dataset_limpio %>%
  mutate(
    categoria_creatinina = cut(
      creatinina,
      breaks = c(-Inf, 0.999, 1.499, 2.999, Inf),
      labels = c("Normal", "Leve", "Moderada", "Severa")
    )
  )

table(dataset_limpio$categoria_creatinina)

  Normal     Leve Moderada   Severa
    3271     7193     2669      199

## Validación final y exportación

Cierre de la limpieza: se descarta el único registro que no puede usarse en el
análisis y se exporta el dataset definitivo, de **13.331 registros**, que es el
que consume el archivo de análisis.

In [128]:

cat("Registros antes de la validacion final:", nrow(dataset_limpio), "\n")

registros_invalidos <- dataset_limpio %>%
  filter(is.na(id_paciente) | is.na(genero) | is.na(categoria_riesgo))

cat("Registros sin identificacion o sin etiqueta clinica:", nrow(registros_invalidos), "\n")
registros_invalidos

dataset_limpio <- dataset_limpio %>%
  filter(!is.na(id_paciente), !is.na(genero), !is.na(categoria_riesgo))

cat("DATASET FINAL:", nrow(dataset_limpio), "registros y",
    ncol(dataset_limpio), "variables\n")
cat("Pacientes unicos:", length(unique(dataset_limpio$id_paciente)), "\n")

Registros antes de la validacion final: 13332
Registros sin identificacion o sin etiqueta clinica: 1

  id_paciente frecuencia_cardiaca frecuencia_respiratoria fecha_hora
1 NA          69                  14                      2024-07-04 22:39:45
  temperatura_corporal saturacion_oxigeno presion_arterial_sistolica
1 NA                   NA                 NA
  presion_arterial_diastolica edad genero ⋯ glucosa colesterol trigliceridos
1 80                          73   NA     ⋯ 103.9   217.2      197.9
  hemoglobina creatinina cantidad_na indicador_anemia indicador_taquicardia
1 13.2        1          6           0                0
  colesterol_alto categoria_creatinina
1 0               Leve

DATASET FINAL: 13331 registros y 36 variables
Pacientes unicos: 13331

In [129]:
# ============================
# EXPORTAR DATASET LIMPIO
# Este archivo es la entrada de 02_analisis.R
# ============================

write.csv(
  dataset_limpio,
  "dataset_limpio.csv",
  row.names = FALSE
)

cat("Archivo guardado: dataset_limpio.csv |", nrow(dataset_limpio), "registros\n")

Archivo guardado: dataset_limpio.csv | 13331 registros

In [130]:
# ============================
# SUBCONJUNTOS DE ANÁLISIS (ACTIVIDAD 7)
# ============================

# 1. Subconjunto Cardiovascular (ahora con indicador_taquicardia)
dataset_cardiovascular <- dataset_limpio %>%
  select(
    id_paciente,
    frecuencia_cardiaca,
    presion_arterial_sistolica,
    presion_arterial_diastolica,
    pam_derivada,
    presion_pulso_derivada,
    vfc_derivada,
    indicador_taquicardia   # NUEVA
  )

# 2. Subconjunto Metabólico
dataset_metabolico <- dataset_limpio %>%
  select(
    id_paciente,
    imc_derivado,
    glucosa,
    colesterol,
    trigliceridos,
    creatinina,
    colesterol_alto,
    indicador_anemia
  )

# 3. Subconjunto Respiratorio
dataset_respiratorio <- dataset_limpio %>%
  select(
    id_paciente,
    frecuencia_respiratoria,
    saturacion_oxigeno,
    hemoglobina,
    indicador_anemia
  )

# ============================
# EXPORTAR LOS 3 SUBCONJUNTOS
# ============================

write.csv(dataset_cardiovascular, "dataset_cardiovascular.csv", row.names = FALSE)
write.csv(dataset_metabolico, "dataset_metabolico.csv", row.names = FALSE)
write.csv(dataset_respiratorio, "dataset_respiratorio.csv", row.names = FALSE)

# Verificar que se crearon los archivos
list.files(pattern = "dataset_")

[1] "dataset_cardiovascular.csv" "dataset_limpio.csv"
[3] "dataset_metabolico.csv"     "dataset_respiratorio.csv"